# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMainWindow(object):
    def setupUi(self, frmMainWindow):
        frmMainWindow.setObjectName("frmMainWindow")
        frmMainWindow.setWindowModality(QtCore.Qt.NonModal)
        frmMainWindow.resize(241, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMainWindow.sizePolicy().hasHeightForWidth())
        frmMainWindow.setSizePolicy(sizePolicy)
        frmMainWindow.setMinimumSize(QtCore.QSize(200, 170))
        self.groupBox = QtWidgets.QGroupBox(frmMainWindow)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 221, 71))
        self.groupBox.setObjectName("groupBox")
        self.cmbLayer = QtWidgets.QComboBox(self.groupBox)
        self.cmbLayer.setGeometry(QtCore.QRect(10, 30, 191, 22))
        self.cmbLayer.setObjectName("cmbLayer")
        self.btnRefresh = QtWidgets.QPushButton(frmMainWindow)
        self.btnRefresh.setGeometry(QtCore.QRect(70, 510, 91, 41))
        self.btnRefresh.setObjectName("btnRefresh")
        self.groupBox_2 = QtWidgets.QGroupBox(frmMainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 221, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cmbX = QtWidgets.QComboBox(self.groupBox_2)
        self.cmbX.setGeometry(QtCore.QRect(10, 30, 191, 22))
        self.cmbX.setObjectName("cmbX")
        self.groupBox_3 = QtWidgets.QGroupBox(frmMainWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 221, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cmbY = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbY.setGeometry(QtCore.QRect(10, 30, 191, 22))
        self.cmbY.setObjectName("cmbY")
        self.groupBox_4 = QtWidgets.QGroupBox(frmMainWindow)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 250, 221, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btnRun = QtWidgets.QPushButton(self.groupBox_4)
        self.btnRun.setGeometry(QtCore.QRect(30, 200, 151, 41))
        self.btnRun.setObjectName("btnRun")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 201, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.txtName = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtName.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.txtName.setObjectName("txtName")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 100, 201, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.cmbLayerCRS = QtWidgets.QComboBox(self.groupBox_6)
        self.cmbLayerCRS.setEnabled(True)
        self.cmbLayerCRS.setGeometry(QtCore.QRect(10, 60, 171, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayerCRS.sizePolicy().hasHeightForWidth())
        self.cmbLayerCRS.setSizePolicy(sizePolicy)
        self.cmbLayerCRS.setObjectName("cmbLayerCRS")
        self.rbProject = QtWidgets.QRadioButton(self.groupBox_6)
        self.rbProject.setGeometry(QtCore.QRect(10, 30, 101, 17))
        self.rbProject.setChecked(True)
        self.rbProject.setObjectName("rbProject")
        self.buttonGroup = QtWidgets.QButtonGroup(frmMainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbProject)
        self.rbLayer = QtWidgets.QRadioButton(self.groupBox_6)
        self.rbLayer.setGeometry(QtCore.QRect(130, 30, 51, 17))
        self.rbLayer.setObjectName("rbLayer")
        self.buttonGroup.addButton(self.rbLayer)
        self.progressBar = QtWidgets.QProgressBar(frmMainWindow)
        self.progressBar.setGeometry(QtCore.QRect(10, 560, 221, 23))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.btnClose = QtWidgets.QPushButton(frmMainWindow)
        self.btnClose.setGeometry(QtCore.QRect(70, 600, 91, 41))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(frmMainWindow)
        QtCore.QMetaObject.connectSlotsByName(frmMainWindow)

    def retranslateUi(self, frmMainWindow):
        _translate = QtCore.QCoreApplication.translate
        frmMainWindow.setWindowTitle(_translate("frmMainWindow", "xyToPoint"))
        self.groupBox.setTitle(_translate("frmMainWindow", "Inputtable or Layer"))
        self.btnRefresh.setText(_translate("frmMainWindow", "Refresh All"))
        self.groupBox_2.setTitle(_translate("frmMainWindow", "Column with X Coordinate Values"))
        self.groupBox_3.setTitle(_translate("frmMainWindow", "Column withY Coordinate Values"))
        self.groupBox_4.setTitle(_translate("frmMainWindow", "Calculated Memory-Pointlayer"))
        self.btnRun.setText(_translate("frmMainWindow", "Create Point Layer"))
        self.groupBox_5.setTitle(_translate("frmMainWindow", "Layername (Input Optional)"))
        self.groupBox_6.setTitle(_translate("frmMainWindow", "Define CRS (optional)"))
        self.rbProject.setText(_translate("frmMainWindow", "Project Settings"))
        self.rbLayer.setText(_translate("frmMainWindow", "Layer"))
        self.btnClose.setText(_translate("frmMainWindow", "Close"))

